name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Ubuntu 20.04
        run: docker build . -t ghcr.io/simnol22/rocketsci:latest -t ghcr.io/simnol22/cxxci:focal --build-arg DISTRO=focal --build-arg COMPILER=10
      
#      - name: Build Ubuntu 22.04
#        run: docker build . -t ghcr.io/simnol22/rocketsci:jammy --build-arg DISTRO=jammy --build-arg COMPILER=12

      - name: Push
        run: docker push --all-tags ghcr.io/simnol22/rocketsci
